version: "3.9"
services:

  mongo1:
    profiles: [db, mongo]
    image: mongo:6.0
    container_name: oli-mongo1
    hostname: mongo1
    networks:
      - dev
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

  redis_db:
    profiles: [db, redis]
    image: redis:6.2
    container_name: oli-redis
    networks:
      - dev
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass olidev
    volumes:
      - redis_data:/data/redis

  backend-core:
    profiles: [core, platform]
    image: core:dev
    container_name: oli-backend-core
    build: ../../backend/core
    environment:
      - PORT=3002
      - NODE_ENV=development
      - COREDB_URL=mongodb://mongo1/
      - DB_CORE=core
      - DB_REPORTS=reports
      - DB_INSPECTORS=inspectors
    networks:
      - dev
    ports:
      - 3002:3002
    volumes:
      - ../../backend/core:/app
      - /app/node_modules
    depends_on:
      - mongo1
      - redis_db

  backend-inspections:
    profiles: [inspector, platform]
    image: inspections:dev
    container_name: oli-backend-inspections
    build: ../../backend/inspections
    environment:
      - PORT=3003
      - NODE_ENV=development
      - COREDB_URL=mongodb://mongo1/
      - DB_CORE=core
      - DB_REPORTS=reports
      - DB_INSPECTORS=inspectors
    networks:
      - dev
    ports:
      - 3003:3003
    volumes:
      - ../../backend/inspections:/app
      - /app/node_modules
    depends_on:
      - mongo1
      - redis_db

  backend-ai-assist:
    profiles: [ai]
    image: ai-assist:dev
    container_name: oli-backend-ai-assist
    build: ../../backend/ai-assist
    environment:
      - NODE_ENV=development
      - PORT=3004
      - COREDB_URL=mongodb://mongo1/
      - REDIS_HOST=redis://redis_db
      - REDIS_PORT=6379
      - REDIS_PASS=olidev
      - DB_CORE=core
      - DB_REPORTS=reports
      - DB_INSPECTORS=inspectors
    networks:
      - dev
    ports:
      - 3004:3000
    volumes:
      - ../../backend/ai-assist:/app
      - /app/node_modules
    depends_on:
      - mongo1
      - redis_db

  frontend-marketing:
    profiles: [marketing]
    image: marketing:dev
    container_name: oli-frontend-marketing
    build:
      dockerfile: Dockerfile
      context: ../../frontend/platform
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - PORT=3000
      - NODE_ENV=development
      - BACKEND_CORE_URL=https://localhost:3002
    networks:
      - dev
    ports:
      - 3000:3000
    volumes:
      - ../../frontend/marketing:/app
      - /app/node_modules
    depends_on:
      - backend-core
      - backend-ai-assist

  frontend-platform:
    profiles: [platform]
    image: platform:dev
    container_name: oli-frontend-platform
    build:
      dockerfile: Dockerfile
      context: ../../frontend/platform
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - PORT=3001
      - NODE_ENV=development
      - BACKEND_CORE_URL=https://localhost:3002
      - BACKEND_INSPECTIONS_URL=https://localhost:3003
      - BACKEND_AIASSIST_URL=https://localhost:3004
    networks:
      - dev
    ports:
      - 3001:3001
    volumes:
      - ../../frontend/platform:/app
      - /app/node_modules
    depends_on:
      - backend-core
      - backend-inspections
      - backend-ai-assist

  mobile-inspector:
    profiles: [mobile, inspector]
    image: inspector:dev
    container_name: oli-mobile-inspector
    build: ../../mobile/inspector
    environment:
      - NODE_ENV=development
      - BACKEND_CORE_URL=https://localhost:3002
      - BACKEND_INSPECTIONS_URL=https://localhost:3003
      - BACKEND_AIASSIST_URL=https://localhost:3004
    networks:
      - dev
    ports:
      - 3005:3000
    volumes:
      - ../../mobile/inspector:/app
      - /app/node_modules
    depends_on:
      - backend-core
      - backend-inspections
      - backend-ai-assist

  mobile-home-owner:
    profiles: [mobile, home-owner]
    image: homeowner:dev
    container_name: oli-mobile-home-owner
    build: ../../mobile/home-owner
    environment:
      - NODE_ENV=development
      - BACKEND_CORE_URL=https://localhost:3002
      - BACKEND_INSPECTIONS_URL=https://localhost:3003
      - BACKEND_AIASSIST_URL=https://localhost:3004
    networks:
      - dev
    ports:
      - 3006:3000
    volumes:
      - ../../mobile/home-owner:/app
      - /app/node_modules
    depends_on:
      - backend-core
      - backend-inspections
      - backend-ai-assist

volumes:
  mongodb_data:
  redis_data:

networks:
  dev:
